//action types are stored here

export const GET_FULL_WEATHER_BEGIN = 'GET_FULL_WEATHER_BEGIN'
export const GET_FULL_WEATHER_SUCCESS = 'GET_FULL_WEATHER_SUCCESS'
export const GET_FULL_WEATHER_FAILURE = 'GET_FULL_WEATHER_FAILURE'
