import { StyleSheet } from 'react-native';
import {
    colors,
    fonts,
    fontSizes,
    fontWeights,
    spacing,
    radius,
} from '../../theme/tokens';

export const styles = StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bgDefault },
    closetBar: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        alignItems: 'center',
    },
    closetTab: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
    },
    closetTabActive: {
        backgroundColor: colors.saveBtnBg,
        borderColor: colors.saveBtnBg,
    },
    closetTabText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
    },
    closetTabTextActive: {
        color: colors.saveBtnText,
        fontWeight: fontWeights.semibold,
    },
    starBadge: { color: '#fbbf24', fontSize: 10 },
    closetCount: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
    },
    newClosetBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    newClosetBtnText: {
        color: colors.textSecondary,
        fontSize: 20,
        lineHeight: 22,
    },
    closetActions: { paddingHorizontal: spacing.md, paddingBottom: spacing.sm },
    actionRow: { flexDirection: 'row', gap: 8 },
    actionBtn: {
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
    },
    actionBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    actionBtnDanger: { borderColor: colors.dangerBorder },
    actionBtnDangerText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.dangerText,
    },
    inlineForm: { flexDirection: 'row', gap: 8, alignItems: 'center' },
    inlineInput: {
        flex: 1,
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    inlineOk: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: colors.saveBtnBg,
        borderRadius: radius.sm,
    },
    inlineOkText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.saveBtnText,
        fontWeight: fontWeights.semibold,
    },
    inlineCancel: { paddingVertical: 8, paddingHorizontal: 10 },
    inlineCancelText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textMuted,
    },
    mainHead: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    mainTitle: {
        fontFamily: fonts.display,
        fontSize: 28,
        color: colors.textPrimary,
    },
    addBtn: {
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: colors.saveBtnBg,
        borderRadius: radius.sm,
    },
    addBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        fontWeight: fontWeights.semibold,
        color: colors.saveBtnText,
    },
    searchBar: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: spacing.md,
        paddingBottom: spacing.sm,
    },
    searchInputWrap: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
        paddingHorizontal: 12,
    },
    searchInput: {
        flex: 1,
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        paddingVertical: 10,
    },
    clearSearch: { color: colors.textMuted, paddingLeft: 8, fontSize: 13 },
    filterBtn: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
    },
    filterBtnActive: { borderColor: colors.textSecondary },
    filterBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    filterPanel: {
        maxHeight: 240,
        borderBottomWidth: 1,
        borderBottomColor: colors.glassBorder,
    },
    filterGroupLabel: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
    },
    chipActive: {
        backgroundColor: colors.saveBtnBg,
        borderColor: colors.saveBtnBg,
    },
    chipText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    chipTextActive: { color: colors.saveBtnText },
    chipColor: { width: 8, height: 8, borderRadius: 4 },
    clearFiltersText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
        textDecorationLine: 'underline',
    },
    legend: {
        flexDirection: 'row',
        gap: 14,
        paddingHorizontal: spacing.md,
        paddingBottom: spacing.sm,
        alignItems: 'center',
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    legendDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    legendLabel: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        marginLeft: 2,
    },
    legendSeason: {
        fontSize: 8,
        color: '#34d399',
    },
    legendClash: {
        fontFamily: fonts.body,
        fontSize: 11,
        color: '#f59e0b',
    },
    legendOOS: {
        width: 10,
        height: 10,
        borderRadius: 2,
        backgroundColor: colors.glassBorder,
        opacity: 0.5,
    },
    articleList: {
        padding: spacing.md,
        gap: spacing.sm,
        paddingBottom: spacing.xl,
    },
    articleCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.glassBg,
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        padding: 10,
    },
    articleCardOOS: { opacity: 0.42 },
    articleImg: {
        width: 48,
        height: 48,
        borderRadius: 8,
        backgroundColor: 'rgba(255,255,255,0.05)',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    articleImgFill: { width: 48, height: 48 },
    warmthDot: {
        position: 'absolute',
        bottom: 3,
        right: 3,
        width: 7,
        height: 7,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.25)',
    },
    articleInfo: { flex: 1, gap: 2 },
    nameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    articleName: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        fontWeight: fontWeights.medium,
        flexShrink: 1,
    },
    seasonBadge: {
        fontSize: 8,
        color: '#34d399',
    },
    articleMeta: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
    },
    articleMetaClash: {
        color: '#f59e0b',
    },
    categoryTag: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
        alignSelf: 'flex-start',
    },
    colorDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
    },
    editBtn: { padding: 8 },
    removeBtn: { padding: 8 },
    microBtnText: {
        fontFamily: fonts.body,
        fontSize: 14,
        color: colors.textMuted,
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.sm,
        padding: spacing.xl,
    },
    emptyTitle: {
        fontFamily: fonts.body,
        fontSize: fontSizes.base,
        color: colors.textSecondary,
    },
});
