import { StyleSheet } from 'react-native';
import {
    ColorTokens,
    fonts,
    fontSizes,
    fontWeights,
    spacing,
    radius,
} from '../../theme/tokens';

export const makeStyles = (colors: ColorTokens) => StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bgDefault },

    // ── Closet tab bar ─────────────────────────────────────────────────────────
    closetBar: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        alignItems: 'center',
    },
    closetTab: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
        flexShrink: 0,   // never compress — scroll instead
    },
    closetTabActive: {
        backgroundColor: colors.saveBtnBg,
        borderColor: colors.saveBtnBg,
    },
    closetTabText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
    },
    closetTabTextActive: {
        color: colors.saveBtnText,
        fontWeight: fontWeights.semibold,
    },
    starBadge: { color: '#fbbf24', fontSize: 10 },
    countBadge: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: radius.pill,
        paddingHorizontal: 6,
        paddingVertical: 2,
        overflow: 'hidden',
    },
    countBadgeActive: {
        color: colors.saveBtnText,
        backgroundColor: 'rgba(0,0,0,0.18)',
        opacity: 0.85,
    },
    newClosetBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    newClosetBtnText: {
        color: colors.textSecondary,
        fontSize: 20,
        lineHeight: 22,
    },

    // ── Inline forms (rename / create) ─────────────────────────────────────────
    inlineForm: { flexDirection: 'row', gap: 8, alignItems: 'center' },
    inlineInput: {
        flex: 1,
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    inlineOk: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: colors.saveBtnBg,
        borderRadius: radius.sm,
    },
    inlineOkText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.saveBtnText,
        fontWeight: fontWeights.semibold,
    },
    inlineCancel: { paddingVertical: 8, paddingHorizontal: 10 },
    inlineCancelText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textMuted,
    },

    // ── Content header row (title + controls) ──────────────────────────────────
    mainHead: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingTop: 4,
        paddingBottom: spacing.sm,
        gap: 6,
    },
    mainTitle: {
        fontFamily: fonts.display,
        fontSize: 26,
        color: colors.textPrimary,
        flex: 1,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    overflowBtn: {
        width: 30,
        height: 30,
        borderRadius: radius.sm,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        alignItems: 'center',
        justifyContent: 'center',
    },
    overflowBtnText: {
        fontSize: 13,
        color: colors.textSecondary,
        letterSpacing: 1.5,
        lineHeight: 16,
    },
    // Single cycling view-mode button
    viewCycleBtn: {
        width: 30,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
    },
    viewCycleBtnText: {
        fontSize: 14,
        color: colors.textSecondary,
    },

    // ── Search + sort + filter row ──────────────────────────────────────────────
    searchBar: {
        flexDirection: 'row',
        gap: 6,
        paddingHorizontal: spacing.md,
        paddingBottom: spacing.sm,
    },
    searchInputWrap: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
        paddingHorizontal: 10,
        gap: 6,
    },
    searchIcon: {
        fontSize: 15,
        color: colors.textMuted,
    },
    searchInput: {
        flex: 1,
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        paddingVertical: 10,
    },
    clearSearch: { color: colors.textMuted, fontSize: 13 },
    sortBtn: {
        width: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
    },
    sortBtnActive: {
        borderColor: colors.textSecondary,
        backgroundColor: colors.glassBgStrong,
    },
    sortBtnText: {
        fontSize: 16,
        color: colors.textSecondary,
    },
    sortBtnTextActive: {
        color: colors.textPrimary,
    },
    filterBtn: {
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        borderRadius: radius.sm,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterBtnActive: { borderColor: colors.textSecondary, backgroundColor: colors.glassBgStrong },
    filterBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    filterPanel: {
        maxHeight: 240,
        borderBottomWidth: 1,
        borderBottomColor: colors.glassBorder,
    },
    filterGroupLabel: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        backgroundColor: colors.glassBg,
    },
    chipActive: {
        backgroundColor: colors.saveBtnBg,
        borderColor: colors.saveBtnBg,
    },
    chipText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    chipTextActive: { color: colors.saveBtnText },
    chipColor: { width: 8, height: 8, borderRadius: 4 },
    clearFiltersText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
        textDecorationLine: 'underline',
    },

    // ── Article list ───────────────────────────────────────────────────────────
    articleList: {
        padding: spacing.md,
        gap: spacing.sm,
        paddingBottom: 96,
    },
    articleCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.glassBg,
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        padding: 10,
        overflow: 'hidden',
    },
    articleCardOOS: { opacity: 0.42 },
    wornAgeBorderRecent: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 3,
        backgroundColor: '#fbbf24',
        borderTopLeftRadius: radius.sm,
        borderBottomLeftRadius: radius.sm,
    },
    wornAgeBorderStale: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 3,
        backgroundColor: 'rgba(99,102,241,0.6)',
        borderTopLeftRadius: radius.sm,
        borderBottomLeftRadius: radius.sm,
    },
    articleImg: {
        width: 52,
        height: 52,
        borderRadius: 10,
        backgroundColor: colors.glassBg,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    articleImgFill: { width: 52, height: 52 },
    warmthDot: {
        position: 'absolute',
        bottom: 3,
        right: 3,
        width: 7,
        height: 7,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.25)',
    },
    articleInfo: { flex: 1, gap: 2 },
    nameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    articleName: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
        fontWeight: fontWeights.medium,
        flexShrink: 1,
    },
    seasonBadge: { fontSize: 8, color: '#34d399' },
    articleMeta: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
    },
    articleMetaClash: { color: '#f59e0b' },
    categoryTag: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        backgroundColor: colors.glassBg,
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
        alignSelf: 'flex-start',
    },
    colorDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
    },

    // ── Empty states ───────────────────────────────────────────────────────────
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.sm,
        padding: spacing.xl,
        paddingTop: spacing.lg,
    },
    emptyTitle: {
        fontFamily: fonts.body,
        fontSize: fontSizes.base,
        color: colors.textSecondary,
    },
    addBtn: {
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: colors.saveBtnBg,
        borderRadius: radius.sm,
    },
    addBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        fontWeight: fontWeights.semibold,
        color: colors.saveBtnText,
    },

    // ── Tile grid ──────────────────────────────────────────────────────────────
    tileGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: spacing.md,
        gap: spacing.sm,
        paddingBottom: 96,
    },
    tileCard: {
        borderRadius: radius.md,
        backgroundColor: colors.glassBg,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        overflow: 'hidden',
    },
    tileCardOOS: { opacity: 0.42 },
    tileImg: {
        width: '100%',
        aspectRatio: 1,
        backgroundColor: colors.glassBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tileImgFill: { width: '100%', height: '100%' },
    tileWarmthDot: {
        position: 'absolute',
        bottom: 6,
        right: 6,
        width: 8,
        height: 8,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.25)',
    },
    tileInfo: { padding: 8, gap: 3 },
    tileNameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    tileName: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        fontWeight: fontWeights.medium,
        color: colors.textPrimary,
        flexShrink: 1,
    },
    tileMeta: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
    },
    tileMetaClash: { color: '#f59e0b' },
    tileColorDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        marginTop: 2,
    },

    // ── TripFit discovery banner ────────────────────────────────────────────────
    tripBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: spacing.md,
        padding: 14,
        backgroundColor: colors.glassBg,
        borderRadius: radius.md,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        // Span full width in both list (column) and tile (row-wrap) layouts
        width: '100%',
    },
    tripBannerIcon: { fontSize: 22 },
    tripBannerInfo: { flex: 1, gap: 2 },
    tripBannerTitle: {
        fontFamily: fonts.bodySemiBold,
        fontSize: fontSizes.sm,
        color: colors.textPrimary,
    },
    tripBannerDesc: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
    },
    tripBannerChevron: {
        fontSize: 20,
        color: colors.textMuted,
    },

    // ── Floating action button ──────────────────────────────────────────────────
    fab: {
        position: 'absolute',
        bottom: 28,
        right: spacing.md,
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: colors.saveBtnBg,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    fabText: {
        fontSize: 28,
        color: colors.saveBtnText,
        lineHeight: 32,
        marginTop: -1,
    },
});
