import { StyleSheet } from 'react-native';
import {
  ColorTokens,
  fonts,
  fontSizes,
  fontWeights,
  spacing,
  radius,
} from '../../theme/tokens';

export const makeSt = (colors: ColorTokens) => StyleSheet.create({
  root:          { flex: 1, backgroundColor: colors.bgDefault },
  header:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.glassBorder },
  title:         { fontFamily: fonts.display, fontSize: 24, color: colors.textPrimary },
  closeBtn:      { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  closeBtnText:  { color: colors.textSecondary, fontSize: 14 },
  body:          { padding: spacing.md, gap: spacing.md, paddingBottom: spacing.xl },
  errorBox:      { padding: spacing.sm, backgroundColor: colors.errorBg, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.errorBorder },
  errorText:     { fontFamily: fonts.body, fontSize: fontSizes.sm, color: colors.errorText },

  imageSection:         { gap: spacing.sm, alignItems: 'center' },
  previewWrap:          { alignItems: 'center', gap: 8 },
  preview:              { width: 100, height: 100, borderRadius: radius.sm },
  clearImg:             { paddingVertical: 4, paddingHorizontal: 12, backgroundColor: colors.dangerBg, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.dangerBorder },
  clearImgText:         { fontFamily: fonts.body, fontSize: fontSizes.xs, color: colors.dangerText },
  imagePlaceholder:     { width: 100, height: 100, borderRadius: radius.sm, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  imagePlaceholderText: { fontFamily: fonts.body, fontSize: fontSizes.xs, color: colors.textMuted },
  imageButtons:         { flexDirection: 'row', gap: spacing.sm },
  imageBtn:             { flex: 1, paddingVertical: 7, paddingHorizontal: spacing.md, backgroundColor: colors.glassBg, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.glassBorder, alignItems: 'center' },
  imageBtnText:         { fontFamily: fonts.body, fontSize: fontSizes.sm, color: colors.textSecondary },

  detectionCard:        { width: '100%', backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder, borderRadius: radius.sm, padding: spacing.sm, gap: 6 },
  detectionLabel:       { fontFamily: fonts.body, fontSize: fontSizes.xs, fontWeight: fontWeights.semibold, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  detectionHeadline:    { fontFamily: fonts.display, fontSize: fontSizes.base, color: colors.textPrimary, fontWeight: fontWeights.semibold },
  detectionRow:         { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  detectionChip:        { paddingVertical: 3, paddingHorizontal: 8, backgroundColor: colors.saveBtnBg, borderRadius: radius.pill },
  detectionChipText:    { fontFamily: fonts.body, fontSize: fontSizes.xs, color: colors.saveBtnText, fontWeight: fontWeights.medium },
  detectionChipMuted:   { backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder },
  detectionChipTextMuted: { fontFamily: fonts.body, fontSize: fontSizes.xs, color: colors.textMuted, fontWeight: fontWeights.medium },
  detectionColors:      { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2 },
  detectionSwatchWrap:  { alignItems: 'center', gap: 3 },
  detectionSwatch:      { width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: colors.glassBorder },
  detectionSwatchLabel: { fontFamily: fonts.body, fontSize: 9, color: colors.textMuted },
  detectionConfidence:  { fontFamily: fonts.body, fontSize: 10, color: colors.textMuted, marginTop: 2 },

  field:         { gap: 6 },
  label:         { fontFamily: fonts.body, fontSize: fontSizes.xs, fontWeight: fontWeights.medium, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  required:      { color: colors.errorText, textTransform: 'none' },
  optional:      { color: colors.textMuted, fontWeight: fontWeights.regular, textTransform: 'none' },
  colorLabel:    { color: colors.textSecondary, fontWeight: fontWeights.regular, textTransform: 'none', letterSpacing: 0 },
  input:         { fontFamily: fonts.body, fontSize: fontSizes.base, color: colors.textPrimary, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: spacing.md },

  chipGrid:      { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  chip:          { paddingVertical: 6, paddingHorizontal: 12, backgroundColor: colors.glassBg, borderWidth: 1, borderColor: colors.glassBorder, borderRadius: radius.pill },
  chipActive:    { backgroundColor: colors.saveBtnBg, borderColor: colors.saveBtnBg },
  chipText:      { fontFamily: fonts.body, fontSize: fontSizes.sm, color: colors.textSecondary },
  chipTextActive:{ color: colors.saveBtnText, fontWeight: fontWeights.semibold },

  typeGroups:     { gap: 12 },
  typeGroup:      { gap: 5 },
  typeGroupLabel: { fontFamily: fonts.body, fontSize: 10, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.8, fontWeight: fontWeights.medium },

  swatchGrid:      { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  swatchRing:      { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: 'transparent' },
  swatchRingActive:{ borderColor: colors.textPrimary },
  swatch:          { width: 26, height: 26, borderRadius: 13, overflow: 'hidden' },

  dangerSection: { borderTopWidth: 1, borderTopColor: colors.glassBorder, paddingTop: spacing.md },
  deleteBtn:     { paddingVertical: 12, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.dangerBorder, backgroundColor: colors.dangerBg, alignItems: 'center' },
  deleteBtnText: { fontFamily: fonts.body, fontSize: fontSizes.base, color: colors.dangerText, fontWeight: fontWeights.medium },

  footer:        { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.glassBorder },
  cancelBtn:     { flex: 1, paddingVertical: 14, backgroundColor: colors.glassBg, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.glassBorder, alignItems: 'center' },
  cancelBtnText: { fontFamily: fonts.body, fontSize: fontSizes.base, color: colors.textSecondary },
  submitBtn:     { flex: 2, paddingVertical: 14, backgroundColor: colors.saveBtnBg, borderRadius: radius.sm, alignItems: 'center' },
  submitBtnText: { fontFamily: fonts.body, fontSize: fontSizes.base, fontWeight: fontWeights.semibold, color: colors.saveBtnText },
});
