import { StyleSheet } from 'react-native';
import {
    ColorTokens,
    fonts,
    fontSizes,
    fontWeights,
    spacing,
    radius,
} from '../../theme/tokens';

export const makeStyles = (colors: ColorTokens) => StyleSheet.create({
    root: { gap: spacing.sm },
    sectionLabel: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
        fontWeight: fontWeights.medium,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    preferredBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 5,
        paddingHorizontal: 10,
        backgroundColor: colors.glassBg,
        borderRadius: radius.pill,
        borderWidth: 1,
        borderColor: colors.glassBorder,
    },
    preferredBadgeText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
    },
    scoreBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: radius.pill,
        borderWidth: 1,
    },
    scoreBadgeText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        fontWeight: fontWeights.semibold,
    },
    pagerCard: {
        gap: spacing.sm,
        paddingBottom: 4,
    },
    pagerCardArticles: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        padding: spacing.sm,
        backgroundColor: colors.glassBg,
        borderRadius: radius.md,
        borderWidth: 1,
        borderColor: colors.glassBorder,
    },
    pagerCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 2,
    },
    pagerSubtitle: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
        fontStyle: 'italic',
    },
    dots: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 2,
    },
    dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: colors.glassBorder,
    },
    dotActive: {
        width: 18,
        height: 6,
        borderRadius: 3,
        backgroundColor: colors.textPrimary,
    },
    headline: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
        lineHeight: fontSizes.sm * 1.5,
    },
    whyText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        fontStyle: 'italic',
        color: colors.textMuted,
        lineHeight: fontSizes.xs * 1.5,
    },
    dotsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.sm,
    },
    resetLink: { paddingVertical: 2, paddingHorizontal: 4 },
    resetLinkText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
        textDecorationLine: 'underline',
    },
    articleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
    articleCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.glassBg,
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        padding: 8,
        flex: 1,
        minWidth: 140,
    },
    articleImg: {
        width: 44,
        height: 44,
        borderRadius: 8,
        backgroundColor: colors.glassBg,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    articleImgFill: { width: 44, height: 44 },
    colorDot: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 8,
        height: 8,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
    },
    articleRemoveBtn: {
        padding: 4,
        marginLeft: 2,
    },
    articleRemoveText: {
        fontSize: 11,
        color: colors.textMuted,
        lineHeight: 14,
    },
    articleLabel: { flex: 1, gap: 2 },
    roleLabel: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    articleName: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textPrimary,
        fontWeight: fontWeights.medium,
    },
    articleMeta: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
    },
    breakdownToggle: { paddingVertical: 6, alignSelf: 'flex-start' },
    breakdownToggleText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
        textDecorationLine: 'underline',
    },
    breakdownRow: { gap: 6 },
    breakdownItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    breakdownLabel: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        width: 46,
    },
    breakdownBarBg: {
        flex: 1,
        height: 4,
        backgroundColor: colors.glassBg,
        borderRadius: 2,
        overflow: 'hidden',
    },
    breakdownBarFill: {
        height: 4,
        backgroundColor: colors.textSecondary,
        borderRadius: 2,
    },
    breakdownValue: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        width: 24,
        textAlign: 'right',
    },
    notesList: { gap: 4 },
    note: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
        lineHeight: fontSizes.xs * 1.5,
    },
    woreThisGlow: {
        marginTop: 4,
        borderRadius: radius.sm,
        borderWidth: 2,
        borderColor: 'rgba(52,211,153,0)',
        shadowOffset: { width: 0, height: 0 },
        shadowRadius: 10,
        elevation: 0,
    },
    woreThisBtn: {
        paddingVertical: 10,
        paddingHorizontal: spacing.md,
        borderRadius: radius.sm - 1,
        borderWidth: 1,
        borderColor: colors.glassBorder,
        alignItems: 'center',
        backgroundColor: colors.glassBg,
    },
    woreThisLogged: {
        borderColor: 'rgba(52,211,153,0.4)',
        backgroundColor: 'rgba(52,211,153,0.08)',
    },
    woreThisText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        color: colors.textSecondary,
    },
    woreThisTextLogged: { color: colors.successText },
    ctaBtn: {
        paddingVertical: 10,
        paddingHorizontal: spacing.md,
        backgroundColor: colors.saveBtnBg,
        borderRadius: radius.sm,
        alignItems: 'center',
        marginTop: 4,
    },
    ctaBtnText: {
        fontFamily: fonts.body,
        fontSize: fontSizes.sm,
        fontWeight: fontWeights.semibold,
        color: colors.saveBtnText,
    },
    closetPicker: { gap: 8, marginTop: 4 },
    closetPickBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        padding: spacing.sm,
        backgroundColor: colors.glassBg,
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
    },
    closetPickName: {
        flex: 1,
        fontFamily: fonts.body,
        fontSize: fontSizes.base,
        color: colors.textPrimary,
    },
    closetPickCount: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
    },
});

export const makeLayerStyles = (colors: ColorTokens) => StyleSheet.create({
    root: {
        gap: 8,
        paddingTop: 4,
        borderTopWidth: 1,
        borderTopColor: colors.glassBorder,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    title: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 1,
        fontWeight: fontWeights.medium,
    },
    confidencePip: {
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: radius.pill,
        borderWidth: 1,
    },
    confidenceText: {
        fontFamily: fonts.body,
        fontSize: 10,
        fontWeight: fontWeights.semibold,
    },
    layerStack: {
        gap: 4,
        paddingVertical: 4,
        paddingHorizontal: 10,
        backgroundColor: colors.glassBg,
        borderRadius: radius.sm,
        borderWidth: 1,
        borderColor: colors.glassBorder,
    },
    layerRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    layerTierLabel: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        width: 36,
    },
    layerRowDivider: {
        width: 1,
        height: 10,
        backgroundColor: colors.glassBorder,
    },
    layerDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
    },
    layerName: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textPrimary,
        flex: 1,
    },
    layerFabric: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
    },
    recommendation: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
        lineHeight: fontSizes.xs * 1.6,
    },
    timeline: { gap: 5, marginTop: 2 },
    timelineRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    timelineTime: {
        fontFamily: fonts.body,
        fontSize: 10,
        color: colors.textMuted,
        width: 68,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    timelineDivider: {
        width: 1,
        height: 10,
        backgroundColor: colors.glassBorder,
    },
    timelineAction: {
        fontFamily: fonts.body,
        fontSize: fontSizes.xs,
        color: colors.textSecondary,
        flex: 1,
    },
});
